language: node_js
node_js:
  - "10"
before_script:
  - npm ci
script: 
  - npm run lint
  - npm run test
  - npm run deploy
  - now alias --token=$ZEIT_KEY -V 2 -n "node_labs" node-labs-execution-$TRAVIS_BRANCH